#!/bin/sh
stch() {
# -e replace {{>}} with a file local to script execution, -e add escapes to $(), -e add escapes to ``, add escapes to POSIX $vars (allow ${var}), -e replace {{!}} commands
val=$(eval "cat << EOF_\$PPID
$(set -e; sed -e 's:{{>\s*\(.*\)\s*}}:{{!cat \1 | stch}}:g' -e 's:$(.*):\\&:g' -e 's:$[[:alpha:]_][[:alnum:]_]*:\\&:g' -e 's:`\(.*\)`:\\`\1\\`:g' -e 's:{{\!\s*\(.*\)\s*}}:$(\1):g')
EOF_\$PPID")
[ "$val" ] && printf "%s\n" "$val"
}

stch
