#!/bin/sh

template_file() {
    printf "Templating stch file %s..." "$1"
    # Overwriting on failure is intended
    if stch "$1" > "$2"; then
        echo "done"
    else
        echo "failed! for $1" >&2
        exit 1
    fi
}

find "${1:-/etc}" -depth -name "*.stch" | while read -r f; do
    template_file "$f" "${f%.*}"
done
